const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "/image/airpods.js",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate adipisci error ut itaque asperiores? Debitis quibusdam eos doloremque odit inventore aut dolorum quas molestiae unde. Beatae similique id accusamus fuga!",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "iPhone 11 Pro 256GB Memory",
    image: "/image/phone.js",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate adipisci error ut itaque asperiores? Debitis quibusdam eos doloremque odit inventore aut dolorum quas molestiae unde. Beatae similique id accusamus fuga!",
    brand: "Apple",
    category: "Electronics",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Amazon Alex",
    image: "/image/phone.js",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate adipisci error ut itaque asperiores? Debitis quibusdam eos doloremque odit inventore aut dolorum quas molestiae unde. Beatae similique id accusamus fuga!",
    brand: "Amazon",
    category: "Electronics",
    price: 52.47,
    countInStock: 7,
    rating: 4.7,
    numReviews: 8,
  },
  {
    _id: "4",
    name: "Came Cannon 80D",
    image: "/image/phone.js",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate adipisci error ut itaque asperiores? Debitis quibusdam eos doloremque odit inventore aut dolorum quas molestiae unde. Beatae similique id accusamus fuga!",
    brand: "Cannon",
    category: "Electronics",
    price: 749.18,
    countInStock: 3,
    rating: 4.8,
    numReviews: 8,
  },
  {
    _id: "5",
    name: "Mouse Logitech",
    image: "/image/phone.js",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate adipisci error ut itaque asperiores? Debitis quibusdam eos doloremque odit inventore aut dolorum quas molestiae unde. Beatae similique id accusamus fuga!",
    brand: "Logitech",
    category: "Electronics",
    price: 33.99,
    countInStock: 7,
    rating: 3.9,
    numReviews: 4,
  },
  {
    _id: "6",
    name: "Playstation 4",
    image: "/image/phone.js",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate adipisci error ut itaque asperiores? Debitis quibusdam eos doloremque odit inventore aut dolorum quas molestiae unde. Beatae similique id accusamus fuga!",
    brand: "Sony",
    category: "Electronics",
    price: 899.99,
    countInStock: 5,
    rating: 5.0,
    numReviews: 5,
  },
];
